import hashlib
import json
import os
import zipfile


def compute_manifest_checksum(manifest: dict) -> str:
    payload = json.dumps(manifest, sort_keys=True, ensure_ascii=False).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def package_skill_zip(manifest: dict, output_dir: str) -> str:
    os.makedirs(output_dir, exist_ok=True)

    skill_id = manifest["skill_id"]
    path = os.path.join(output_dir, f"{skill_id}.dhskill.zip")

    out = dict(manifest)
    out["checksum"] = compute_manifest_checksum(out)

    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("manifest/skill.json", json.dumps(out, indent=2, ensure_ascii=False))
        zf.writestr("docs/README.txt", "Devils Hand skill package generated by skill_packer.py")
        zf.writestr("visual/profile.json", json.dumps(out.get("visual_profile", {}), indent=2))

    return path
